require 'i18n'
require 'leafleter'
require 'overhelper'
require 'rest_client'
require 'persistent-cache'
require 'digest/sha1'

require_relative 'bicycle_report/bicycle_parking.rb'
require_relative 'bicycle_report/bicycle_ways.rb'
require_relative 'bicycle_report/crossing.rb'
require_relative 'bicycle_report/report_generator.rb'